// <auto-generated />
namespace DeveloperTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class kunal_07_01_2020_modify_tbl_message_second_time : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kunal_07_01_2020_modify_tbl_message_second_time));
        
        string IMigrationMetadata.Id
        {
            get { return "202001071849435_kunal_07_01_2020_modify_tbl_message_second_time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
